version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Type the command to log in to your Docker Hub account here.          
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 120523844784.dkr.ecr.eu-west-3.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd backend/
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"toh-backend","imageUri":"%s"}]' $IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
      - pwd
      - ls
artifacts:
  files: 
    - './imagedefinitions.json'
  name: backend_build_output